# Site settings
title: The Blog of Tombert
email: thomas@gebert.sexy
description: > # this means to ignore newlines until "baseurl:"
  These are basically the inane ramblings of a guy who likes to program
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tombert.github.io" # the base hostname & protocol for your site
github_username:  tombert
twitter_username: realtombert
comments: true
# Build settings
markdown: kramdown
paginate: 10
gems:
- jemoji
- jekyll-sitemap
